val pow=<ore:gunpowder>;
val hipow=<flansmod:highexgunpowder>;
val ingot=<ore:ingotIron>;
val fiber=<flansmod:fiberglass>;
val wood=<ore:logWood>;
val glass=<ore:paneGlassColorless>;
val redstone=<ore:dustRedstone>;
#add
val shell=<contenttweaker:brass_cartridge_case>;
val pipe=<immersiveengineering:material:14>;
val plate=<ore:plateSteel>;
val plank=<ore:plankTreatedWood>;
val rod=<ore:stickSteel>;
val comp=<immersiveengineering:material:9>;
#Zombie
#   Guns
mods.immersiveengineering.Blueprint.addRecipe("gun_zombie",<flansmod:winchestermodel70>,[pipe*2,comp,plate*8,plank*8,glass*4]);
mods.immersiveengineering.Blueprint.addRecipe("gun_zombie",<flansmod:3006bullet>,[shell,pow]);
mods.immersiveengineering.Blueprint.addRecipe("gun_zombie",<flansmod:shulkersniperammo>,[<ore:plateTungsten>,<ore:shulkerShell>,hipow]);
mods.immersiveengineering.Blueprint.addRecipe("gun_zombie",<flansmod:m4carbine>,[rod*2,pipe,comp*2,plate*10]);
mods.immersiveengineering.Blueprint.addRecipe("gun_zombie",<flansmod:m4carbineammo>,[plate*3,shell*10,pow*3]);
mods.immersiveengineering.Blueprint.addRecipe("gun_zombie",<flansmod:mp5k>,[pipe,comp,plate*7]);
mods.immersiveengineering.Blueprint.addRecipe("gun_zombie",<flansmod:mp5kammo>,[plate*2,shell*5,pow*2]);
mods.immersiveengineering.Blueprint.addRecipe("gun_zombie",<flansmod:smg100ammo>,[fiber*6,pow*9]);
mods.immersiveengineering.Blueprint.addRecipe("gun_zombie",<flansmod:olympia>,[ingot*12,<ore:plankWood>*8]);
mods.immersiveengineering.Blueprint.addRecipe("gun_zombie",<flansmod:doublebarrelledshotgun>,[ingot*8,<ore:plankWood>*6]);
mods.immersiveengineering.Blueprint.addRecipe("gun_zombie",<flansmod:12gaugeshell>,[ingot,pow]);
mods.immersiveengineering.Blueprint.addRecipe("gun_zombie",<flansmod:12gaugeshellincendiary>,[ingot,pow*3]);
#   Pistols
mods.immersiveengineering.Blueprint.addRecipe("gun_zombie",<flansmod:coltpython>,[ingot*8]);
mods.immersiveengineering.Blueprint.addRecipe("gun_zombie",<flansmod:357magnum>,[ingot,pow]);
mods.immersiveengineering.Blueprint.addRecipe("gun_zombie",<flansmod:highexpistolammo>,[ingot,hipow]);
mods.immersiveengineering.Blueprint.addRecipe("gun_zombie",<flansmod:appistolammo>,[ingot,hipow,<ore:gemPrismarine>]);
mods.immersiveengineering.Blueprint.addRecipe("gun_zombie",<flansmod:flaregun>,[ingot*9]);
mods.immersiveengineering.Blueprint.addRecipe("gun_zombie",<flansmod:flaregunammo>,[ingot*2,pow*2,redstone]);
mods.immersiveengineering.Blueprint.addRecipe("gun_zombie",<flansmod:glock>,[ingot*9]);
mods.immersiveengineering.Blueprint.addRecipe("gun_zombie",<flansmod:glockammo>,[ingot*4,pow*3]);
mods.immersiveengineering.Blueprint.addRecipe("gun_zombie",<flansmod:usppoisonammo>,[ingot*2,pow*2,<minecraft:spider_eye>*2]);
#   Misc
mods.immersiveengineering.Blueprint.addRecipe("gun_zombie",<flansmod:beartrap>,[ingot*12]);
#Modern
#   Rifles
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_a",<flansmod:dragunov>,[ingot*12,wood*10,glass*4]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_a",<flansmod:dragunovammo>,[ingot*4,pow*3]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_a",<flansmod:m14>,[ingot*10,fiber*10]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_a",<flansmod:m14ammo>,[ingot*2,pow*3]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_a",<flansmod:g3>,[ingot*22]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_a",<flansmod:g3ammo>,[ingot*4,pow*4]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_a",<flansmod:tripletake>,[ingot*12,fiber*8]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_a",<flansmod:tripletakeammo>,[fiber*5,pow*4]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_a",<flansmod:sg550>,[ingot*16,fiber*2]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_a",<flansmod:sg550ammo>,[ingot*5,pow*4]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_a",<flansmod:seekerrifleammo>,[fiber*4,hipow*2,<minecraft:ender_eye>]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_a",<flansmod:flanmw2xscope>,[ingot*7,<ore:paneGlassColorless>*2]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_a",<flansmod:flanmw4xscope>,[ingot*6,<ore:ingotGold>,<ore:paneGlassColorless>*2]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_a",<flansmod:flanmw8xscope>,[ingot*6,<ore:gemDiamond>,<ore:paneGlassColorless>*2]);
#   Assault
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_a",<flansmod:m16a4>,[ingot*15,fiber*5]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_a",<flansmod:m16a4ammo>,[ingot*4,pow*5]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_a",<flansmod:mtar>,[ingot*6,fiber*10]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_a",<flansmod:mtarammo>,[fiber*4,pow*3]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_a",<flansmod:fnscar>,[ingot*6,fiber*10]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_a",<flansmod:fnscarammo>,[fiber*3,pow*4]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_a",<flansmod:acr>,[ingot*6,fiber*12]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_a",<flansmod:acrammo>,[fiber*2,pow*3]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_a",<flansmod:aug>,[ingot*8,fiber*8]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_a",<flansmod:augammo>,[fiber*3,pow*3]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_a",<flansmod:adar15>,[ingot*8,fiber*8]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_a",<flansmod:adar15ammo>,[fiber*3,pow*4]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_a",<flansmod:an94>,[ingot*12,fiber*3]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_a",<flansmod:an94ammo>,[ingot*2,pow*4]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_a",<flansmod:ash12>,[ingot*22]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_a",<flansmod:ash12ammo>,[fiber*5,pow*3]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_a",<flansmod:galil>,[ingot*5,fiber*15]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_a",<flansmod:galilammo>,[ingot*2,fiber*2,pow*3]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_a",<flansmod:famas>,[ingot*6,fiber*14]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_a",<flansmod:famasammo>,[ingot*5,pow*3]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_a",<flansmod:betacmag>,[fiber*8,pow*10]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_a",<flansmod:apcrrifleammo>,[fiber*6,hipow*3]);
#   AKs
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_b",<flansmod:ak47>,[ingot*10,wood*10]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_b",<flansmod:ak47ammo>,[ingot*5,pow*4]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_b",<flansmod:ak74>,[ingot*15,fiber*10]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_b",<flansmod:ak74ammo>,[ingot*3,fiber*4,pow*3]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_b",<flansmod:rpd>,[ingot*20,wood*5]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_b",<flansmod:rpdammo>,[ingot*12,pow*11]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_b",<flansmod:rpk>,[ingot*12,wood*8]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_b",<flansmod:rpkammo>,[ingot*6,pow*4]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_b",<flansmod:witheringakammo>,[ingot*4,<minecraft:skull:1>,pow*3]);
#   SMGs
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_b",<flansmod:mp5>,[ingot*15]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_b",<flansmod:mp5ammo>,[fiber*3,pow*4]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_b",<flansmod:skorpion>,[ingot*12,wood*3]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_b",<flansmod:skorpionammo>,[fiber*3,pow*4]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_b",<flansmod:mp7>,[ingot*14]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_b",<flansmod:mp7ammo>,[ingot*4,pow*4]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_b",<flansmod:fmg>,[ingot*5,fiber*8]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_b",<flansmod:uzi>,[ingot*14]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_b",<flansmod:uziammo>,[fiber*4,pow*4]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_b",<flansmod:smg100ammo>,[fiber*6,pow*9]);
#   Shotguns
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_b",<flansmod:w1200>,[ingot*16,fiber*6]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_b",<flansmod:m1014>,[ingot*12,fiber*10]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_b",<flansmod:r870>,[ingot*12,wood*4]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_b",<flansmod:spas>,[fiber*10,ingot*4]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_b",<flansmod:m1887>,[ingot*6,wood*4]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_b",<flansmod:12gbirdshotammo>,[<ore:nuggetIron>*6,pow]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_b",<flansmod:12gbuckshotammo>,[<ore:nuggetIron>*3,pow]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_b",<flansmod:12gslugammo>,[ingot,pow]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_b",<flansmod:12gheammo>,[fiber*6,hipow]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_b",<flansmod:12gflechetteammo>,[fiber,pow]);
#   Pistols
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_c",<flansmod:m9>,[ingot*8]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_c",<flansmod:m9ammo>,[ingot*2,pow*2]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_c",<flansmod:usp>,[ingot*10]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_c",<flansmod:uspammo>,[ingot*2,pow*2]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_c",<flansmod:m1911>,[ingot*8,<ore:leather>]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_c",<flansmod:m1911ammo>,[ingot*2,pow]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_c",<flansmod:sigp226>,[ingot*8]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_c",<flansmod:sigp232>,[ingot*8]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_c",<flansmod:sigp226ammo>,[ingot*2,pow*2]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_c",<flansmod:makarov>,[ingot*8]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_c",<flansmod:makarovammo>,[ingot*2,pow]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_c",<flansmod:glock>,[ingot*9]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_c",<flansmod:glockammo>,[ingot*4,pow*3]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_c",<flansmod:deserteagle>,[ingot*12]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_c",<flansmod:deserteagleammo>,[ingot*3,pow*2]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_c",<flansmod:kcasmartpistol>,[ingot*12]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_c",<flansmod:kcasmartcarbineammo>,[ingot*3,pow*2]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_c",<flansmod:usppoisonammo>,[ingot*3,pow,<minecraft:ender_eye>]);
#   Misc
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_c",<flansmod:m67>,[fiber*4,pow*2]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_c",<flansmod:hydra70ammo>,[ingot*19,pow*19]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_c",<flansmod:hellfire>,[ingot*2,fiber*4,pow*4,redstone*2]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_c",<flansmod:trigat>,[ingot*2,fiber*4,pow*5,redstone*2]);
#Modernadvanced
#   Rifles
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_adv_1",<flansmod:m21>,[ingot*10,fiber*10,glass*5]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_adv_1",<flansmod:m21ammo>,[ingot*2,fiber*3,pow*3]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_adv_1",<flansmod:l96>,[ingot*10,fiber*12,glass*5]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_adv_1",<flansmod:l96ammo>,[fiber*3,pow*3]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_adv_1",<flansmod:ntw20>,[ingot*10,fiber*4]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_adv_1",<flansmod:ntw20ammo>,[fiber*3,pow*3]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_adv_1",<flansmod:seekerrifleammo>,[fiber*4,hipow*2,<minecraft:ender_eye>]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_adv_1",<flansmod:flanmw2xscope>,[ingot*7,<ore:paneGlassColorless>*2]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_adv_1",<flansmod:flanmw4xscope>,[ingot*6,<ore:ingotGold>,<ore:paneGlassColorless>*2]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_adv_1",<flansmod:flanmw8xscope>,[ingot*6,<ore:gemDiamond>,<ore:paneGlassColorless>*2]);
#   Snipers
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_adv_1",<flansmod:m40a3>,[ingot*12,fiber*8,glass*4]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_adv_1",<flansmod:r700>,[ingot*10,wood*8,glass*4]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_adv_1",<flansmod:eldiablo>,[ingot*10,fiber*18]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_adv_1",<flansmod:sniperammo>,[ingot*12,pow]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_adv_1",<flansmod:hesniperammo>,[ingot*12,hipow]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_adv_1",<flansmod:shulkersniperammo>,[<ore:shulkerShell>,hipow]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_adv_1",<flansmod:flanmw2xscope>,[ingot*7,<ore:paneGlassColorless>*2]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_adv_1",<flansmod:flanmw8xscope>,[ingot*6,<ore:gemDiamond>,<ore:paneGlassColorless>*2]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_adv_1",<flansmod:barrett>,[ingot*20,<ore:rodBlaze>]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_adv_1",<flansmod:barrettammo>,[ingot*4,pow*3]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_adv_1",<flansmod:kcasmart50>,[ingot*20,fiber*10,<ore:gemQuartz>*5]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_adv_1",<flansmod:kcasmart50ammo>,[ingot*4,pow*3]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_adv_1",<flansmod:barrettexplosiveammo>,[ingot*4,hipow*5]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_adv_1",<flansmod:barrettcompactammo>,[ingot*4,hipow*5]);
#   Assault
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_adv_1",<flansmod:kcasmartcarbine>,[ingot*20,fiber*9,redstone*7]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_adv_1",<flansmod:kcasmartcarbineammo>,[fiber*3,hipow,<minecraft:ender_eye>]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_adv_1",<flansmod:l86>,[ingot*20,fiber*5]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_adv_1",<flansmod:l86ammo>,[ingot*10,pow*9]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_adv_1",<flansmod:hk416>,[ingot*12,fiber*8]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_adv_1",<flansmod:g36>,[ingot*5,fiber*15]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_adv_1",<flansmod:g36ammo>,[ingot*2,fiber*4,pow*4]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_adv_1",<flansmod:hcar>,[fiber*24]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_adv_1",<flansmod:hcarammo>,[fiber*6,pow*3]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_adv_1",<flansmod:betacmag>,[fiber*8,pow*10]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_adv_1",<flansmod:apcrrifleammo>,[fiber*6,hipow*3]);
#   LMGs
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_adv_2",<flansmod:m249>,[ingot*24,fiber*5]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_adv_2",<flansmod:m249ammo>,[ingot*10,fiber*10,pow*10,<ore:dyeCyan>]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_adv_2",<flansmod:m60>,[ingot*24]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_adv_2",<flansmod:m60ammo>,[ingot*9,fiber*3,pow*10]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_adv_2",<flansmod:devotionx55>,[ingot*24]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_adv_2",<flansmod:devotionx55ammo>,[ingot*9,fiber*3,pow*10]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_adv_2",<flansmod:pr3>,[ingot*10,fiber*12,<ore:ingotGold>*6]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_adv_2",<flansmod:pr3ammo>,[ingot*9,fiber*3,pow*10]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_adv_2",<flansmod:pr3oscammo>,[ingot*10,fiber*3,hipow*3]);
#   SMGs
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_adv_2",<flansmod:p90>,[ingot*5,fiber*20]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_adv_2",<flansmod:p90>,[fiber*8,pow*6]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_adv_2",<flansmod:bizon>,[ingot*12,fiber*8]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_adv_2",<flansmod:bizonammo>,[ingot*5,pow*4]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_adv_2",<flansmod:krissvector>,[ingot*12,fiber*20]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_adv_2",<flansmod:krissvectorammo>,[fiber*8,pow*6]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_adv_2",<flansmod:honeybadger>,[ingot*12,fiber*8]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_adv_2",<flansmod:honeybadgerammo>,[fiber*5,pow*4]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_adv_2",<flansmod:smg100ammo>,[fiber*6,pow*9]);
#   Shotguns
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_adv_2",<flansmod:judge>,[ingot*8,fiber*4]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_adv_2",<flansmod:executioner>,[ingot*10,wood*6]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_adv_2",<flansmod:aa12>,[ingot*12,fiber*12]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_adv_2",<flansmod:peacekeeper>,[ingot*8,wood*5]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_adv_2",<flansmod:12gbirdshotammo>,[<ore:nuggetIron>*6,pow]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_adv_2",<flansmod:12gbuckshotammo>,[<ore:nuggetIron>*3,pow]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_adv_2",<flansmod:12gslugammo>,[ingot,pow]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_adv_2",<flansmod:12gheammo>,[fiber,hipow]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_adv_2",<flansmod:12gincendiaryammo>,[fiber,pow,<ore:dustLava>]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_adv_2",<flansmod:mastiff1218>,[ingot*8,fiber*12]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_adv_2",<flansmod:mastiff1218ammo>,[ingot*3,pow]);
#   Specials
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_sp",<flansmod:minigun>,[ingot*32,fiber*16,redstone*16]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_sp",<flansmod:minigunammo>,[ingot*8,pow*32]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_sp",<flansmod:gau19>,[ingot*48,fiber*16,redstone*16]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_sp",<flansmod:gau19ammo>,[ingot*8,pow*16]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_sp",<flansmod:minigunexplosiveammo>,[ingot*8,hipow*32]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_sp",<flansmod:minigunportableammo>,[ingot*2,pow*6]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_sp",<flansmod:jury>,[ingot*10]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_sp",<flansmod:juryammo>,[ingot,pow]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_sp",<flansmod:highexpistolammo>,[ingot,hipow]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_sp",<flansmod:appistolammo>,[ingot,hipow,<ore:gemPrismarine>]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_sp",<flansmod:b4crossbow>,[ingot*24,fiber*12,<ore:string>]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_sp",<flansmod:b4crossbowammo>,[ingot,<ore:itemRawFlint>]);
#   Rockets
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_exp",<flansmod:rpg>,[ingot*25,wood*10]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_exp",<flansmod:rpgammo>,[ingot*5,pow*6]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_exp",<flansmod:m72law>,[ingot*12,fiber*8]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_exp",<flansmod:m72lawammo>,[ingot*3,pow*5]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_exp",<flansmod:at4>,[fiber*5,ingot*4]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_exp",<flansmod:at4ammo>,[ingot*3,pow*5]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_exp",<flansmod:stinger>,[ingot*20,wood*10,redstone*20]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_exp",<flansmod:stingerammo>,[ingot*12,<ore:ingotGold>*4,pow*12,redstone*6]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_exp",<flansmod:mlrs6>,[ingot*20,fiber*8]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_exp",<flansmod:mlrs6ammo>,[fiber*4,pow*5]);
#   Explosives
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_exp",<flansmod:gl1>,[ingot*12,wood*6]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_exp",<flansmod:gl6>,[ingot*20,fiber*12]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_exp",<flansmod:grenadelauncherammo>,[ingot*3,pow*5]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_exp",<flansmod:grenadelauncherincendiaryammo>,[ingot*3,pow*3,<ore:dustLava>*2]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_exp",<flansmod:grenadelauncherbouncyammo>,[ingot*3,pow*5]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_exp",<flansmod:grenadelaunchergasammo>,[ingot*3,pow*3,<minecraft:spider_eye>*4]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_exp",<flansmod:claymore>,[fiber*4,pow*2,redstone]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_exp",<flansmod:c4remote>,[fiber,redstone]);
mods.immersiveengineering.Blueprint.addRecipe("gun_modern_exp",<flansmod:c4>,[pow*3,<ore:slimeball>*2,redstone]);