
[general]
	#The alternative names of this material.
	alternativeNames = []
	#The byproducts of this material.
	extras = []
	#The module blacklist of this material.
	moduleBlacklist = []
	#Should items of this material have the enchanted glow.
	hasEffect = false
	#The model type of the material.
	modelType = "crystal"
	#The color of this material.
	color = 5411708

[exnihilocreatio]
	#The default base to sieve in Ex Nihilo Creatio to get this material.
	oreBase = "#gravel"

[exnihilosequentia]
	#The output chance of the sieve recipes added using an iron mesh.
	sieveIronChance = 0.00800000037997961
	#The output chance of the sieve recipes added using a diamond mesh.
	sieveDiamondChance = 0.01600000075995922

