
[general]
	#The alternative names of this material.
	alternativeNames = []
	#The byproducts of this material.
	extras = []
	#The module blacklist of this material.
	moduleBlacklist = []
	#Should items of this material have the enchanted glow.
	hasEffect = false
	#The model type of the material.
	modelType = "metallic"
	#The color of this material.
	color = 1711914

[mekanism]
	#The default base to use in Mekanism's Combiner to recreate ores.
	oreBase = "minecraft:cobblestone"

[magneticraft]
	#The default byproduct material to output in Magneticraft's grinder.
	grinderByproduct = "minecraft:gravel"
	#The default byproduct material to output in Magneticraft's sluice box.
	sluiceBoxByproduct = "minecraft:cobblestone"

[molten]
	#The temperature of this molten fluid.
	temperature = 1000

